spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_thymeleaf_mybatis?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.coding.boot.tm.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
mapper:
  mappers:
    - cn.coding.boot.tm.utils.MyMapper
  not-empty: true
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    cn.coding.boot.tm.mapper: DEBUG